name: smart_cradle_for_baby_care_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # Audio
  just_audio: ^0.9.46
  # path
  image_picker: ^1.0.7
  file_picker: ^10.1.1
  path: ^1.9.0
  open_file: ^3.5.10
  # Icons
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  # Responsive UI
  flutter_screenutil: ^5.9.3
  # Icon App
  font_awesome_flutter: ^10.7.0
  # SVG Image
  #flutter_svg: ^2.0.17
  # Charts
  fl_chart: ^0.69.0
  simple_animation_progress_bar: ^1.8.2
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  # Stata Management
  flutter_bloc: ^8.1.6
  # Local DB
  shared_preferences: ^2.5.2
  # HTTP Client
  dio: ^5.8.0+1
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  #
  intl: ^0.18.0
  easy_date_timeline: ^0.1.1
  animated_toggle_switch: ^0.8.4
  path_provider: ^2.1.5
  #camera
  http: ^0.13.6
  flutter_mjpeg: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/
    - Assets/Audios/

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins-Black.ttf
          weight: 900
        - asset: Assets/Fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: Assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: Assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: Assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: Assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: Assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: Assets/Fonts/Poppins-ExtraLight.ttf
          weight: 200

    - family: Roboto
      fonts:
        - asset: Assets/Fonts/Roboto-Black.ttf
          weight: 900
        - asset: Assets/Fonts/Roboto-Bold.ttf
          weight: 700
        - asset: Assets/Fonts/Roboto-Medium.ttf
          weight: 500
        - asset: Assets/Fonts/Roboto-Regular.ttf
          weight: 400
        - asset: Assets/Fonts/Roboto-Light.ttf
          weight: 300
        - asset: Assets/Fonts/Roboto-Thin.ttf
          weight: 100
